### ISSUE TITLE
Request for Access to MERFISH Pre-trained Model

### ISSUE THREAD

**Issue by MNXIAOJIA123** [Patchouli-M/SequencingCancerFinder#12]
I am particularly interested in the pre-trained model applied to the MERFISH dataset (550 genes) mentioned in the paper. If possible, could you kindly share the pre-trained files for this model? Thank you very much.

**Comment by Patchouli-M** [comment]
Thank you for your interest in our work.

the pre-trained model and the gene list for [Merfish](https://drive.google.com/file/d/1J-XcAGLlW3qy08ovX4y343DR8PwzRKz6) have been uploaded. 

Since this is based on an earlier version of the experimental code, you might need to make some minor modifications and verify the results, especially concerning the model definition and loading process.

Additionally, please note that the model's predictions require threshold adjustment before outputting the results. For a more detailed discussion of this, please refer to Supplementary Note 5 and Supplementary Figure 7 in the paper.

**Comment by MNXIAOJIA123** [comment]
Thank you very much for your help

**Comment by MNXIAOJIA123** [comment]
Thank you very much for your help. In addition, may I ask how to get the malignant cell annotation or cell type annotation of the MERFISH datasets mentioned in the paper? From the website (https://info.vizgen.com/ffpe-showcase) seems to be unable to find the annotation of the MERFISH datasets. Thanks

**Comment by Patchouli-M** [comment]
Oh, I'm not sure how to obtain completely precise annotations either. In Figure 4 of the paper, regarding the MERFISH results, I only compared the model's output with the expression of the marker gene of cancer cells.
The genes detected by MERFISH are selected. for example, in cancer-related MERFISH datasets, genes that are known to be associated with cancer are typically chosen. Perhaps you could consider doing further annotations from this perspective?

**Comment by MNXIAOJIA123** [comment]
Thank you very much. You're so kind
